// <auto-generated />
using System;
using FocusFlowAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusFlowAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214061454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FocusFlowAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "PlaceholderHash12345"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            Email = "test@example.com",
                            FirstName = "Test",
                            LastName = "Client",
                            PasswordHash = "PlaceholderHash54321"
                        });
                });

            modelBuilder.Entity("FocusFlowAPI.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EstimatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Development",
                            DueDate = new DateTime(2025, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedTime = new TimeSpan(0, 4, 30, 0, 0),
                            Priority = 1,
                            Status = "In Progress",
                            Title = "Set up API Endpoint",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Development",
                            CompletionDate = new DateTime(2025, 1, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedTime = new TimeSpan(0, 2, 0, 0, 0),
                            Priority = 2,
                            Status = "Done",
                            Title = "Define User Model",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Testing",
                            DueDate = new DateTime(2025, 1, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedTime = new TimeSpan(0, 1, 0, 0, 0),
                            Priority = 3,
                            Status = "Open",
                            Title = "Review Task Requirements",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FocusFlowAPI.Models.UserTask", b =>
                {
                    b.HasOne("FocusFlowAPI.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FocusFlowAPI.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
